### ISSUE TITLE
`<lastmod>` field is updated even though the page didn't change

### ISSUE THREAD

**Issue by iampava** [iamvishnusankar/next-sitemap#101]
**Describe the bug**
`<lastmod>` field is always equal to the timestamp of the sitemap generation

**To Reproduce**

1. Create a new NextJS app using `npx create-next-app`
2. Add this package and configure it using `sitemap.js`
3. Build the project
4. Generate `sitemap.xml` once
5. Have a look at the `<lastmod>` tag which has the current time as value
5. Generate `sitemap.xml` again without changing the code
6. The `<lastmod>` tag is updated even though we haven't changed the contents of the pages

**Expected behavior**
The `<lastmod>` tag should only update if the file itself changed. 

<hr>

I think it should keep a hash based on the filename or file content, and only if that's different change the `<lastmod>` value.

**Comment by iamvishnusankar** [comment]
@iampava It's a complex scenario. For example, If you're using image loaders on a page, parsed image paths will change with each build id. 

Even though human readable contents are not changing during a page build, there are chances for image/cacheable url changes. That's why the default `lastmod` is always set to page build time.

If you don't want this behaviour, you can use `transform` function to provide custom `lastmod` timestamp.

**Comment by iampava** [comment]
Got it. Thanks!

**Comment by iampava** [comment]
Tried to implement it myself but it seems that the `transform` function doesn't work in an asynchronous scenario. Am I right?

**Comment by iamvishnusankar** [comment]
@iampava Just added support. It will be released soon.

**Comment by iampava** [comment]
Thanks. For now we'll remove the `lastmod` completely in our project, and will come back to this when it's done.
