### ISSUE TITLE
Add "/" to index path

### ISSUE THREAD

**Issue by maxeth** [iamvishnusankar/next-sitemap#221]
Google always indexes index URLs with a ```/``` at the end of the URL, and from what I know it is generally common to always add the ```/```  to the index page. 

Yet, next-sitemap adds the index page as ```url.com``` without ```/```, which results in the Google Search console saying that the index page is not included in any sitemap, because it is looking for the version with an ```/``` at the end.

I would like next-sitemap to include the ```/``` at the website's index path in the sitemap or at least give us an option to do so, or are there any reasons that speak against it?

I've already tried doing something like returning the path ```//``` in the ```transform``` function instead of ```/```, but the ```/``` just doesn't get added to the sitemap no matter what. 

Are there potentially any existing solutions to this already?

**Comment by vinaynair39** [comment]
What if I just want to add the trailing slash to the home page?

**Comment by AaronMcCloskey** [comment]
I'm also having the same issue. I only want the trailing slash on the index URL. And not on other pages. Is this possible?

**Comment by alexhooley** [comment]
@iamvishnusankar this should be reopened, the [Sitemap schema](https://www.sitemaps.org) is quite clear that a trailing slash on the index should be used even when trailing slashes aren't enabled on the other pages.

> This URL must begin with the protocol (such as http) and end with a trailing slash, if your web server requires it. This value must be less than 2,048 characters.

- [Sample XML Sitemap](https://www.sitemaps.org/protocol.html#sitemapXMLExample)
- [Do URLs in the Sitemap need to be completely specified?](https://www.sitemaps.org/faq.html#faq_url_format)
- [NextJS.org's own sitemap](https://nextjs.org/sitemap.xml)

The [default Next.js behaviour](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash) is to redirect trailing slash to non-trailing slash. 
> By default Next.js will redirect urls with trailing slashes to their counterpart without a trailing slash.

However this doesn't apply to the root index because [as Google themselves put it](https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash#your-sites-configuration-and-your-options) "Rest assured that for your root URL specifically, `https://example.com` is equivalent to `https://example.com/` and can't be redirected even if you're Chuck Norris."

Try the [with-next-sitemap](https://github.com/vercel/next.js/tree/canary/examples/with-next-sitemap) example locally and you can see the issue: 

1. The base URL has a trailing slash by default: `http://localhost:3000/` (the trailing slash is **visually hidden** by your browser's address box. That trailing slash does exist though, and you can copy/paste the URL from your browser into a text file to see the full URL **with** the trailing slash)
2. The other URLs don't have trailing slashes by default: `http://localhost:3000/page-1`
3. The sitemap generated by `next-sitemap` is therefore wrong according to Sitemap schema as the trailing slash is missing on `http://localhost:3000`:
```xml
<url>
<loc>http://localhost:3000</loc>
<lastmod>2023-08-23T16:14:37.863Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>http://localhost:3000/page-1</loc>
<lastmod>2023-08-23T16:14:37.863Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>
</url>
```

**Comment by masanori-iwata** [comment]
@iamvishnusankar,

I'm reaching out to inquire if there has been any progress on the issue discussed earlier. Unfortunately, the workaround of setting trailingSlash to true does not resolve the problem we're encountering. It appears that this behavior is not aligned with Next.js's default behavior, where only the homepage is expected to have a trailing slash by default.

> @iamvishnusankar this should be reopened, the [Sitemap schema](https://www.sitemaps.org) is quite clear that a trailing slash on the index should be used even when trailing slashes aren't enabled on the other pages.
> 
> > This URL must begin with the protocol (such as http) and end with a trailing slash, if your web server requires it. This value must be less than 2,048 characters.
> 
> * [Sample XML Sitemap](https://www.sitemaps.org/protocol.html#sitemapXMLExample)
> * [Do URLs in the Sitemap need to be completely specified?](https://www.sitemaps.org/faq.html#faq_url_format)
> * [NextJS.org's own sitemap](https://nextjs.org/sitemap.xml)
> 
> The [default Next.js behaviour](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash) is to redirect trailing slash to non-trailing slash.
> 
> > By default Next.js will redirect urls with trailing slashes to their counterpart without a trailing slash.
> 
> However this doesn't apply to the root index because [as Google themselves put it](https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash#your-sites-configuration-and-your-options) "Rest assured that for your root URL specifically, `https://example.com` is equivalent to `https://example.com/` and can't be redirected even if you're Chuck Norris."
> 
> Try the [with-next-sitemap](https://github.com/vercel/next.js/tree/canary/examples/with-next-sitemap) example locally and you can see the issue:
> 
> 1. The base URL has a trailing slash by default: `http://localhost:3000/` (the trailing slash is **visually hidden** by your browser's address box. That trailing slash does exist though, and you can copy/paste the URL from your browser into a text file to see the full URL **with** the trailing slash)
> 2. The other URLs don't have trailing slashes by default: `http://localhost:3000/page-1`
> 3. The sitemap generated by `next-sitemap` is therefore wrong according to Sitemap schema as the trailing slash is missing on `http://localhost:3000`:
> 
> ```
> <url>
> <loc>http://localhost:3000</loc>
> <lastmod>2023-08-23T16:14:37.863Z</lastmod>
> <changefreq>daily</changefreq>
> <priority>0.7</priority>
> </url>
> <url>
> <loc>http://localhost:3000/page-1</loc>
> <lastmod>2023-08-23T16:14:37.863Z</lastmod>
> <changefreq>daily</changefreq>
> <priority>0.7</priority>
> </url>
> ```

**Comment by samparmenter** [comment]
Please re-open this as we wish to do the same and there isn't any way to add the trailing slash to just the homepage right now.
