### ISSUE TITLE
Incremental sitemap generation

### ISSUE THREAD

**Issue by alexandersch** [iamvishnusankar/next-sitemap#31]
What if I add a new page through my CMS, but don't do a new build. Instead, I use [ISR](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration) with `fallback: true`. This would result in a newly statically generated page on the fly (without running a full build).

What would be the best way to trigger a new sitemap build? Or maybe a better solution would be a way to also incrementally add this page to the sitemap?

**Comment by iamvishnusankar** [comment]
That's an interesting use case. This package relies on the `build-manifest` and `prerender-manifest`. It's unaware of next.js runtime. Because of this it would be hard to support ISR. 

In theory, next-sitemap will add ISR contents to sitemap file if next runtime is adding the newly generated page info to `pretender-manifest` and we're able to run the `next-sitemap` script. But that's not possible currently as `next` doesn't provide any callback hooks for ISR. (Feel free to correct me on this)

Another way of doing this would be to watch file changes and running `next-sitemap` script. Watching file changes will create unnecessary overheads for the server. So the best solution for now would be to do periodic builds using a CI/CD pipeline.

**Comment by alexandersch** [comment]
I also think the idea of watching for file changes is not the way to go. For now a periodic build using CI/CD would suffice. Maybe NextJS could implement a callback hook to the ISR. That would be the ultimate solution.

**Comment by dayvista** [comment]
Perhaps this could be achieved using a dynamic SSR `sitemap.xml` page located at the route `/pages/sitemap.xml.js` (like [this approach](https://leerob.io/blog/nextjs-sitemap-robots#dynamic-sitemaps).

Maybe a function from `next-sitemap` could be run, or `build-manifest`/`prerender-manifest` rewritten, in `getServerSideProps`. Just an idea - I don't know much about the internals of this library or the build step of Next.js.

**Comment by AlexTechNoir** [comment]
I was thinking that if library needs to run a script to create a sitemap, then what if we run script programmatically inside getStaticProps with ISR? A new sitemap will be created on incoming request and on time interval. I've looked it up and found [this](https://stackoverflow.com/a/38032376/10489004) example. Does anybody know if this code can solve the problem?

```
import { series } from 'async'
const { exec } = require('child_process')

const fetcher = url => fetch(url).then(r => r.json())

export async function getStaticPaths() {
  const pages = await fetcher(`${url}/pages)
  const paths = pages.map(page => ({
    params: { id: page.id.toString() }
  }))

  return { paths, fallback: false }
}

export async function getStaticProps({ params }) {
  const page = await fetcher(`${url}/pages/${params.id}`)

  // Launching script to create a sitemap
  series([
    () => exec('npm run postbuild') 
  ])

  return { 
    props: { params, page }, 
    revalidate: 10
  }
}
```
