### ISSUE TITLE
Why is sitemap-0.xml generated for small sites?

### ISSUE THREAD

**Issue by benjaminhoffman** [iamvishnusankar/next-sitemap#344]
**Describe the bug**
When I first installed this package, it generated `sitemap.xml`.  Earlier this year, my site started generating a `sitemap-0.xml` file. It's a small site of <20 URLs so no need for multiple sitemaps.

Is this a bug I introduced or a feature of this package? I read https://github.com/iamvishnusankar/next-sitemap/issues/318 but it didn't help much because I really just want `sitemap.xml` only.

My package.json:
```
{
  "build": "next build",
  "postbuild": "next-sitemap"
  "devDependencies": {
      ....
      "next-sitemap": "^2.5.14", 
  }
}

```
My next-sitemap.js
```
module.exports = {
  siteUrl: "example.com",
  generateRobotsTxt: true,
  changefreq: "daily",
  priority: 0.7,
  exclude: [ ...  ],
};
```

**To Reproduce**
`npm run build`

**Expected behavior**
Since I have a small site, I expect to have only `sitemap.xml` file. No need for split sitemap files.

**Comment by iamvishnusankar** [comment]
@benjaminhoffman `sitemap.xml` is index sitemap. You only need to submit this index sitemap to search engines.

Please read: https://github.com/iamvishnusankar/next-sitemap#index-sitemaps

**Comment by benjaminhoffman** [comment]
@iamvishnusankar yes i am aware (I moonlight as an SEO lol)... but what I'm saying is that for small sites, it would be nice to _just_ have a `sitemap.xml`... no need for `sitemap-0.xml`... feels like it's overkill.

If this is how this package works, no worries then... I just wanted to make sure I didn't break something in my config.

**Comment by JuroUhlar** [comment]
I second this. I have a small site and expected a simple `sitemap.xml`. 

Generating a sitemap index that links to the actual sitemap is just... weird. It forced me spend time re-reading the docs to make sure something is not wrong with my config. I concluded it's probably fine and submitted my code. But then other team members though it was weird too, so I had to spend more time on Google, learning how sitemap indexes work and making sure that having an index instead of a single sitemap is not somehow worse for SEO.

It also breaks some sitemap validation tools that are like "Paste the URL of your site here... Sitemap is valid!". But it only validates the sitemap index, not the actual sitemap. Like, I understand that going for an index every time probably streamlines the code, but it goes against user expectation. It would be more intuitive if the output was just a single sitemap.xml for small sites (maybe make the limit configurable). Thanks for your consideration! :)

**Comment by CloutProject** [comment]
I strongly agree with what @JuroUhlar said. I'll personally stick to 1.9.12 for now.

**Comment by benjaminhoffman** [comment]
im not sure -- but i already removed this plugin from my repo and now just manually create my sitemap... there's just too many [issues](https://github.com/iamvishnusankar/next-sitemap/issues/217) blocking me for it to be useful

**Comment by FitFingers** [comment]
> Where is the option to disable this and revert back to a single sitemap.xml file?

You can downgrade back to a previous version of `next-sitemap`: I rolled it back from version `^2.5.20` to `^1.6.168` and now it works correctly.

**Comment by isaachinman** [comment]
@iamvishnusankar Would you accept a PR to introduce a configuration option to control the index vs no-index behaviour?

**Comment by iamvishnusankar** [comment]
@isaachinman That would be great! Feel free to send it.

**Comment by isaachinman** [comment]
Just spent a few minutes digging into the source code here, as I've never worked on (or used) this project before. Above all else, I am surprised and impressed with the quality. Anyways, it looks like things are pretty deeply set up to expect a sitemap index output.

I won't have time to work on this today, but for anyone else interested, or my future self, it's probably best to start at [the end](https://github.com/iamvishnusankar/next-sitemap/blob/master/packages/next-sitemap/src/sitemap-index/export.ts#L15) and work backwards from there.

**Comment by iamvishnusankar** [comment]
@benjaminhoffman, @JuroUhlar, @CloutProject, @dkodeit, @FitFingers, @isaachinman

Refactored the entire project and added support for disabling index-sitemap generation along with ESM support.

**Comment by isaachinman** [comment]
Wow, cheers @iamvishnusankar! Massive PR – how do you normally handle reviews?

**Comment by iamvishnusankar** [comment]
@isaachinman Thanks! Yes this is indeed a big refactoring. However, I kept all the tests from previous version, so chances for breaking will be minimal.

Currently this PR is stuck due to a windows specific issue. https://github.com/iamvishnusankar/next-sitemap/runs/6704441467?check_suite_focus=true#step:7:143

**Comment by benjaminhoffman** [comment]
yes i noticed, thank you! we're adding it back on our roadmap to re-implement in our app. we only have 5 pages but add'l complexity around `noindex` etc. will report back if I see any issues. thx again!
