### ISSUE TITLE
Inject environment variables

### ISSUE THREAD

**Issue by arvigeus** [iamvishnusankar/next-sitemap#38]
Use case: I have NEXT_PUBLIC_DEPLOYMENT_URL. In order to read it I have to use manually `dotenv`, which is not ideal.

**Comment by iamvishnusankar** [comment]
Hi @arvigeus, Injecting environment variables are not in the scope of this project. If you're building the project on any `CI` server, you can inject the environment variable as build step and use `process.env` along with a fallback url.

```
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_DEPLOYMENT_URL || 'https://example.com'
}
```

Closing this issue for now, feel free to reopen it if you need further help regarding this.

**Comment by reubn** [comment]
While I'd agree that injecting environment variables wouldn't be in scope for a _standalone_ sitemap generator, I don't agree that it shouldn't be in scope for _this_ project: given its tight coupling with Next.js.

Next.js injects environment variables. If this was a normal Next.js plugin (i.e. one that made use of webpack / the `next.config.js` file) then the variables **would** be injected. It's only due to the mechanism behind this plugin that they aren't - but to ensure a consistent DX, surely it would be preferable that they are.

It's a 2 line fix with no dependencies other than Next.js itself:

``` js
const env = require('@next/env')

env.loadEnvConfig(process.cwd(), process.env.NODE_ENV === 'development')
```

**Comment by ilgarm** [comment]
Would be nice to have this, having an integration with env files of next.js would be smooth. @iamvishnusankar any luck to get this one? Thank you!

**Comment by iamvishnusankar** [comment]
@reubn I totally missed this since you commented on a closed issue. I have added support for .env loading. Consider mentioning my username or reopen the issue next time.

@ilgarm It's here.

**Comment by ilgarm** [comment]
Thank you! Works as expected.
