### ISSUE TITLE
[next-sitemap] Unable to find export-maker

### ISSUE THREAD

**Issue by Mbensler** [iamvishnusankar/next-sitemap#534]
**Describe the bug**

I am receiving an error with next-sitemap. See attached images.

My project is being built directly from github to vercel.

It used to work but no longer does. I have no idea what went wrong though.

My next-sitemap.config.js config is as follows: 
```js
// https://www.npmjs.com/package/next-sitemap

/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://myRealURLisHere/',
  generateRobotsTxt: true, // (optional)
  // ...other options
};

```

**To Reproduce**

- Unknown

**Screenshots**

![Skærmbillede 2022-11-23 111356](https://user-images.githubusercontent.com/3165204/203521520-7f993536-6c5c-465d-9092-f37394635cc8.png)
![Skærmbillede 2022-11-23 111345](https://user-images.githubusercontent.com/3165204/203521536-4b01e116-3c56-4434-99df-7264868ffefa.png)

**Comment by iamvishnusankar** [comment]
@Mbensler Please provide a reproduction

**Comment by fahimuddin-brillmark** [comment]
@iamvishnusankar What is the solution for this? having same issue, how it is completed?

**Comment by andreas-bergstrom** [comment]
I am getting this after upgrading to Next 13.1.5, works again after downgrading back to 13.0.7.

**Comment by felixh10r** [comment]
I isolated the problem to node 14, it works after updating to node 16. May be a combination of node 14 and next 13 for all I know 🤔

**Comment by sshah98** [comment]
I'm getting this issue too -- unsure how to fix

**Comment by apuntovanini** [comment]
Having this issue as well, any ideas?

**Comment by IcarusHU** [comment]
Hi, any update on this matter?
Having the same issue on node 18.12.1 with Next 13.1.1, but also tried with Next 13.0.7. The site is in a Turbo monorepo, but the paths seem to be correct; Tried changing/sync sourceDir, next.conf distDir, run the build from root, from app-root;   obviously the postbuild runs correctly with npmrc enable-pre-post-scripts=true, but the outcome is always the same. This is extremely frustrating. I'm pretty sure by now, that I do something wrong, because there were so few issue report I've found, but no clue at all.

**Comment by apuntovanini** [comment]
Be sure you run same versions locally and in Vercel, my issue was fixed upgrading node version from Vercel settings to 16

**Comment by IcarusHU** [comment]
Thanks, but that wasn't the issue, but after about 6 hours of debugging and wondering in the bushes (caused by 6 overlapping trivial trifles), I'll better get back after sleep and write down the journey.

**Comment by iamvishnusankar** [comment]
Can someone provide a reproduction for this? I'm unable to reproduce the bug in my machine.

**Comment by IcarusHU** [comment]
Hi, basically the issue comes up in case .next build dist folder is not yet set. Since it's working into .next folder by default. In our case there were other overlapping tiny issues lead us into the woods (like working in monorepo with pnpm, etc.), with the error, we thought there is a path issue somewhere at first and then we thought it's something else, so several times focusing on an overlapping issues. (also we still use localhost:3000 for our temp backend, which made the build get mixed up with it.)

And the error message said 'cant't find export-maker.json', which is a typo, because export-marker.json is the one missing. But it was generally our fault.

What I would suggest to you is to fix the typo mentioned, and I would add a line into the documentation, to 'make sure the build dist folder is different from the dev '.next' folder and set parallelly and consistently in next.config and next-sitemap.config most importantly in case someone uses SSR requests. It would help juniors to not get lost with such a case as ours. 

But otherwise, we messed up because of our infra a little bit. So no need to reproduce :)

**Comment by 7hakurg** [comment]
This is one of those issues that I am facing for too long but haven't been able to fix this. In my situation I am using Next 13.1.6 and Node 18* 

I am using edge function on Vercel. If I remove the patch for edge function from the function that is 
export const config = {
  runtime: "edge",
};

My application builds in vercel but other wise it is not.

**Comment by rennehir** [comment]
I'm also experiencing this issue, when building locally. I am using Node v18.13.0 and Next.js v13.1.6 in a Turborepo. I started suddenly experiencing these today without touching anything in the code that would affect the functionality of `next-sitemap`. Which is also frustrating that it doesn't happen every time, and therefore quite hard to reproduce.

**Comment by 7hakurg** [comment]
There is a work around, in next-config, I updated swcMinify as True and this solved the issue for me for now.

**Comment by rennehir** [comment]
Thanks @7hakurg, at least now I got it to build successfully. Still can't figure out why everything worked in the morning and the suddenly it wasn't able to find the `export-maker` 🤔

**Comment by rennehir** [comment]
Actually now I got the error again despite the `swcMinify` set to true in `next.config.js`. I was able to narrow down the problem though.

If I have `i18n` settings in `next.config.js` I get the error from `next-sitemap` but if I disable the `i18n` settings the build succeeds.

**Comment by 7hakurg** [comment]
I had this i18n settings too but for me it worked fine.

**Comment by KirschX** [comment]
I was experiencing same issue, but after I removed node_modules and reinstalled the package multiple times, problem just solved, but still don't know why...

**Comment by rennehir** [comment]
Yep, reinstalling node_modules and building without cache worked, but not everytime. Now I haven't had any problems, but still not quite confident that the issue has actually solved

**Comment by machineghost** [comment]
I removed `node_modules` and `package-lock.json`, did a complete reinstall (`npm i`), and ... I'm still getting the error, on two different computers.

Really frustrating bug.
