### ISSUE TITLE
Update sitemap file with fallback route 

### ISSUE THREAD

**Issue by Sangdt** [iamvishnusankar/next-sitemap#68]
I have a large e-commerce site with about 100+ product pages and i only create about 5-10 pages at build times with fallback:true  . So the sitemap file created at build time didnt have all the actual pages in the cms, do i need to update it with the fallback route created by nextjs later on or i need fetch all the route in the cms ?

**Comment by kamilms21** [comment]
I have exactly the same problem. Is it possible to use fallback: true with this package?

**Comment by nagman** [comment]
Same here. There is no way to have the production sitemap automatically updated without having to trigger a build each time a new page is created (from an external source, like a CMS).

So I had to give up with this package and finally implemented my own sitemap builder by following this guide: https://leerob.io/blog/nextjs-sitemap-robots

And here's what my sitemap looks like:
```typescript
// src/pages/sitemap.xml/index.tsx

import { GetServerSidePropsContext } from 'next';
import { request } from 'utils/api'; // it's a homemade function I use to query a GraphQL API
import postsQuery from './posts.graphql'; // and that's my GraphQL request

const host = 'https://foobar.com';

// All my known static pages go here
const staticRoutes = [
	'/',
	'/news',
	'/testimonies',
	'/contact',
	'/about',
];

function Sitemap() {}

type Posts = Record<'news' | 'testimonies', { slug: string }[]>;

export async function getServerSideProps({ res }: GetServerSidePropsContext) {
	// All the dynamic posts are fetched by a GraphQL request
	const posts = await request<Posts>(postsQuery);
	const dynamicRoutes = Object.entries(posts).map(([key, value]) =>
		value.map(({ slug }) => `/${key}/${slug}`),
	);
	const routes = [staticRoutes, dynamicRoutes].flat(2);

	res.setHeader('Content-Type', 'text/xml');
	res.write(
		`<?xml version="1.0" encoding="UTF-8"?>
		<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
			${routes.map((route) => `<url><loc>${host}${route}</loc></url>`).join('')}
		</urlset>`,
	);
	res.end();
	return { props: {} }; // you need to provide this last line or next will throw some warnings in the console, as it expects you to provide some page props
}

export default Sitemap;
```
Which will generate entries for:
- /
- /news
- /news/post-slug-1
- /news/post-slug-2
- /news/post-slug-3
- /testimonies
- /testimonies/post-slug-1
- /testimonies/post-slug-2
- /testimonies/post-slug-3
- /contact
- /about

This method uses `getServerSideProps` which is processed each time the page is requested (we don't care the build time as it's only meant for bots, not for users). So our sitemap is always up-to-date.

**Comment by erwanriou** [comment]
At the end i used this solution too, until this library handle the multi domains, locale.

**Comment by iamvishnusankar** [comment]
@Sangdt This package focuses on static/pre-render based sitemaps. It's because this packages relies on nextjs internal manifest files to determine the created pages. Also data sourcing is out of the context of `next-sitemap`. So, as of now, it will not be possible to use `fallback:true` with this package. 

@nagman As mentioned above, this package relies on post-build manifest. So, dynamic content is out of the context of this package. Also in your example, you can use `next-sitemap` along with your custom solution for dynamic content. Serve the sitemaps for your dynamic content from `dynamic-sitemap.xml/index.tsx` and list the dynamic sitemap page in `robotTxtOptions.additionalSitemaps`

```
module.exports = {
  siteUrl: 'https://example.com',
  generateRobotsTxt: true,
  robotsTxtOptions: {
    additionalSitemaps: [
      'https://example.com/dynamic-sitemap.xml',  // <==== here
    ],
  },
}
```

In this way, `next-sitemap` will manage the sitemaps for all your static content and add your dynamic sitemap will be added to `robots.txt`
