### ISSUE TITLE
sitemap not generated for static routes

### ISSUE THREAD

**Issue by EniasCailliau** [iamvishnusankar/next-sitemap#697]
**Describe the bug**
I'm running sitemap but the sitemap is empty even though I have staticRoutes listed in routes-manifest.json.

Here's an excerpt of my .next/routes-manifest.json

{
    "version": 3,
    "pages404": true,
    "caseSensitive": false,
    "basePath": "",
    "redirects": [
        {
            "source": "/:path+/",
            "destination": "/:path+",
            "internal": true,
            "statusCode": 308,
            "regex": "^(?:/((?:[^/]+?)(?:/(?:[^/]+?))*))/$"
        }
    ],
    "headers": [],
        "dynamicRoutes": [],
         "staticRoutes": [
        {
            "page": "/",
            "regex": "^/(?:/)?$",
            "routeKeys": {},
            "namedRegex": "^/(?:/)?$"
        },
        {
            "page": "/account",
            "regex": "^/account(?:/)?$",
            "routeKeys": {},
            "namedRegex": "^/account(?:/)?$"
        },
        {
            "page": "/blog",
            "regex": "^/blog(?:/)?$",
            "routeKeys": {},
            "namedRegex": "^/blog(?:/)?$"
        },
        {
            "page": "/blog/about",
            "regex": "^/blog/about(?:/)?$",
            "routeKeys": {},
            "namedRegex": "^/blog/about(?:/)?$"
        }]
        }
        

I'm using app router and the following directory structure: 

/app/(website)/account

Tried several tutorials and for all of them the sitemap is auto-generated for static pages. So any pointers in the right direction would be super helpful.

**Comment by iamvishnusankar** [comment]
@EniasCailliau Can you provide a reproduction?

**Comment by EniasCailliau** [comment]
Should I give you access to my repo?

**Comment by thejessewinton** [comment]
+1, having the same issue here.

**Comment by LedzZm** [comment]
The module uses the manifest, created by next on build, to create the static paths.

Are you maybe running just the postbuild script when testing?

**Comment by thejessewinton** [comment]
No, still happens when I run `next build`, and is present in prod.

**Comment by patricksevat** [comment]
I think I found the issue, it took me quite some hours and it might be that my root cause is not the same as your root cause, so I'll add some debug details as well.

In short, for me the issue is that I'm using `fetch(url, {cache: process.env.NODE_ENV === 'production' ? 'no-store' : 'default'})`. This triggers a non-reported `staticGenerationStore.dynamicUsageErr` deep in NextJS ([node_modules/next/dist/server/app-render/app-render.js:453](https://github.com/vercel/next.js/blob/85606472e40d9a314511d763ec788727d55b2214/packages/next/src/server/app-render/app-render.tsx#L723-L725)).

It kinda makes sense not to report it since I put it there myself, but still it had this weird unexpected outcome that next-sitemap stopped working.

Reproduction path for this, within next-sitemap context would be to change `examples/app-dir/app/[dynamic]/page.tsx` to

```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const DynamicPage: React.FC<any> = async ({ params }) => {
  const status = await getFooStatus();

  return (
    <div>
      <h1>DynamicPage Component</h1>
      <pre>{JSON.stringify(params, null, 2)}</pre>
      <code>status ${status}</code>
    </div>
  )
}

export default DynamicPage

/**
 * @see https://beta.nextjs.org/docs/api-reference/generate-static-params
 * @returns
 */
export async function generateStaticParams() {
  return [...Array(10)].map((_, index) => ({
    dynamic: `page-${index}`,
  }))
}

async function getFooStatus () {
  const fooData = await fetch(`https://google.com?`, {
    cache: process.env.NODE_ENV === 'production' ? 'no-store' : 'default',
  });
  return fooData.status;
}
```

<details><summary>Debug details</summary>
<ul>
<li> In general, for next-sitemap to pick up your page it should be present in `.next/prerender-manifest.json`</li>
<li> If its not there, you can search in `node_modules/next/dist/build/index.js` for `finalPrerenderRoutes[page] = {...}`</li>
<li> `finalPrerenderRoutes` will only be set if we have the correct **revalidate** value. The key line here is `revalidate = exportConfig.initialPageRevalidationMap[route]`</li>
<li> Working back from there, `exportConfig.initialPageRevalidationMap` is set in that same file, however, the actual values are set in `await exportApp(dir, exportOptions, nextBuildSpan)`</li>
<li> This leads to `examples/app-dir/node_modules/next/dist/export/index.js`, where the key line is `nextConfig.initialPageRevalidationMap[path] = result.fromBuildExportRevalidate;`</li>
<li> The `result` property here comes from `await exportPageOrApp()` which is invoking `node_modules/next/dist/export/worker.js`. Note that this is a worker that gets spawned, so using the regular debugger and stepping into this function will not work. You'll need to manually set a `debugger` statement in that worker.js file</li>
<li> Allright, still with me? Cool, now in the worker.js file, we're looking for `fromBuildExportRevalidate`, which in my case was dependent on the outcome of `renderToHTMLOrFlight()`, but in your case it might be different, so I'll stop here</li>

Happy debugging 😅 


</ul>
</details>

**Comment by JakovGlavac** [comment]
Check the docs: https://next-sitemap.iamvishnusankar.com/docs/documentation/dynamic-sitemaps
